#' Print rmaxent lambdas objects
#'
#' Print method for \code{lambdas} objects generated by \code{\link{parse_lambdas}}.
#'
#' @param x A \code{lambdas} object returned by \code{\link{parse_lambdas}}.
#' @param digits The minimum number of significant digits to be used.
#' @param ... Other arguments to \code{\link{print.data.frame}}.
#' @keywords maxent, lambdas
#' @seealso \code{\link{parse_lambdas}} \code{\link{project}}
#' @export
#' @details This function summarises the \code{data.frame} holding feature 
#'   weights in an \code{rmaxent} \code{lambdas} object. To see that information
#'   in full for \code{lambdas} object \code{x}, use \code{x$lambdas} or
#'   \code{unclass(x)}. See \code{str(x)} to examine the structure of an
#'   object of \code{lambdas} class.
print.lambdas <- function(x, digits=4, ...) {
  nonzero <- subset(
    x$lambdas[, c('feature', 'lambda', 'min', 'max', 'type')], 
    lambda != 0)
  zero <- subset(
    x$lambdas[, c('feature', 'lambda', 'min', 'max', 'type')], 
    lambda == 0)
  if(nrow(nonzero) > 0) {
    cat('\nFeatures with non-zero weights\n\n')
    print(nonzero, row.names=F, digits=digits, ...)
    cat('\n')
  }
  if(nrow(zero) > 0) {
    cat('\nFeatures with zero weights\n\n')
    print(zero, row.names=FALSE, digits=digits, ...)  
    cat('\n')
  }
  # meta <- t(as.data.frame(x[-1]))
  # dimnames(meta) <- list(
  #   c('Linear predictor normalizer', 'Density normalizer', 
  #     'Number of background points', 'Entropy'), ''
  # )
  # cat('\n---\n')
  # print(meta, digits=digits)
}
